# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86f06d5e94b078009774a55fa49c1be4c96f14294884b4b37bc2bd7770e17a4b5f86fe6c8bc0351afac0a53d384af16c5dec954343cf30bd1c65a5f373b140bc

test:
  secret_key_base: 4adf0b154026657bed62d1094c6a1cb4f7259b2c5953b6bd04827020b14255754c8ea0941886fa549effabc85b2568e2e14b2e58ea073a4a84ad3e5ceaf87ca1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
