# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#######

# Create default admin
User.create(email: "admin@example.com",  password: "password", password_confirmation: "password")

# G+, flickr, youtube
smp = SocialMediaPlatform.create(title: "Google+", color: "#000000", font_awesome_style: "fa fa-google-plus")

question = Question.create( question_title: "What are some keywords related to the subject matter that was censored",
			               question_type: "text",
			               required_field: true,
			               placeholder: "eg: free speech, mark zuckerberg, etc")

page = Page.create(social_media_platform_id: smp.id)
PagesQuestion.create(question_id: question.id, page_id: page.id)


SocialMediaPlatform.create(title: "Flickr", color: "#000000", font_awesome_style: "fa fa-flickr")
SocialMediaPlatform.create(title: "YouTube", color: "#000000", font_awesome_style: "fa fa-youtube")
SocialMediaPlatform.create(title: "Twitter", color: "#000000", font_awesome_style: "fa fa-twitter")
SocialMediaPlatform.create(title: "Facebook", color: "#000000", font_awesome_style: "fa fa-facebook")



# Create the CMS pages
ContentManagementPage.create(page: "what-we-do" , content: '<div class=row><div class=col-md-12><div class="text-box clearfix"><div class=row><div class="col-md-6 image-wrapper"><img src=/assets/post-image.png></div><div class="col-md-6 col-md-offset-6"><div class=post-content><h2>ABOUT ONLINECENSORSHIP.ORG</h2><p>Sites like Facebook, Twitter, Instagram, YouTube and Google+ have an outsized impact in our social lives. We treat these platforms as a “public sphere”, using them to discuss issues both controversial and menial, to connect with friends far and near, and to engage in activism and debate. But while these platforms may be used by the public, they’re ultimately owned by private companies with their own rules and systems of governance that control—and in some cases, censor—users’ content.</p><p>OnlineCensorship.org seeks to encourage companies to operate with greater transparency and accountability toward their users as they make decisions that regulate speech. We know they’re big fans of data—so we’re collecting reports from their users in an effort to shine a light on what content is taken down, why companies make certain decisions about content, and how content takedowns are affecting communities of users around the world.</p><p>By collecting these reports, we’re not just looking for trends. We’re also looking for context, and to build an understanding of how the removal of content affects users’ lives. Often the communities that are most impacted by online censorship are also the most marginalized—so the people that are censored are also those that are least likely to be heard. Our aim is to amplify those voices and help them to advocate for change.</p></div></div></div></div></div></div><div class=white-box><h2>HOW THE SITE WORKS</h2><div class=row><div class=col-md-6><p>Has your post, photo, status, video or tweet been blocked or deleted?<br>OnlineCensorship.org gives social media users a place to report taken down notices and catalog content that has been removed. Simply follow our easy submission process to let us know how a platform has censored your content.</p></div><div class=col-md-6><p>Our reporting tool will take you through a series of questions about the content and the process through which you were notified by the company. Although you may remain anonymous, we ask that you provide as much information as possible.</p></div></div><div class=row><div class=col-md-6><h3>The information that you share with us will be used in four ways:</h3></div></div><div class=row><ol class="oc-uses clearfix"><li class="col-md-3 col-no-padding dark-blue-bg"><p>To learn more about how social media companies enforce their terms of service.</p></li><li class="col-md-3 col-no-padding medium-blue-bg"><p>To understand how content takedown and account deactivation practices affect the lives and work of individuals in different parts of the world.</p></li><li class="col-md-3 col-no-padding dark-blue-bg"><p>To engage with companies on how they can improve their rules and enforcement mechanisms to be more compatible with the principles of free expression.</p></li><li class="col-md-3 col-no-padding medium-blue-bg"><p>To raise public awareness about the ways that social media companies regulate speech.</p></li></ol></div><p>For more about the project’s motivations and plans, please see our<%= link_to "Frequently Asked Questions page", root_path %></p></div>')
ContentManagementPage.create(page: "who-we-are" , content: '<div class="col-md-6 image-wrapper"><img src=/assets/post-image.png></div><div class="col-md-6 col-md-offset-6"><div class=post-content><p>OnlineCensorship.org is a project of the Electronic Frontier Foundation and Visualizing Impact. It was founded in 2012 by Ramzi Jaber and Jillian C. York, both of whom had begun to notice posts disappearing from their friends’ Facebook pages.</p><p>One particular story inspired them to action: popular band Coldplay posted a link to OneWorld’s song <a href="">“Freedom for Palestine”</a>, a multi-artist collaboration, generating nearly 7,000 largely supportive comments.<br>Then, suddenly, the link disappeared, leading to accusations that the band had taken it down due to criticism. As it turned out, <a href="">it wasn’t Coldplay that removed the link</a>, but Facebook, after it was reported as “abusive” by scores of users.<br>The lack of recourse for such takedowns led to the creation of OnlineCensorship.org, a platform where users of social media sites can report content takedowns. In 2014, we won the Knight News Challenge on the topic of strengthening the Internet for free expression and innovation and were finally able to move the project forward.</p><div class=links><a href="" class=more-link>EFF Website</a> <a href="" class=more-link>VISUALIZING IMPACT Website</a></div></div></div>')
ContentManagementPage.create(page: "privacy-policy" , content: '<div class=white-box><div class=row><div class=col-md-10><div class=privacy-section><h2>Section Title</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique facilisis bibendum. Duis dictum, justo ac egestas accumsan, est magna porta nunc, at ultricies elit urna nec eros. Etiam arcu velit, posuere sed ante quis, placerat mattis ipsum. Vestibulum rhoncus ex quis nibh ornare, ut eleifend justo mollis. Vivamus pretium nunc non ante commodo, nec varius ligula sollicitudin. Nam id pulvinar sem. Suspendisse.</p></div><div class=privacy-section><h2>Section Title</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique facilisis bibendum. Duis dictum, justo ac egestas accumsan, est magna porta nunc, at ultricies elit urna nec eros. Etiam arcu velit, posuere sed ante quis, placerat mattis ipsum. Vestibulum rhoncus ex quis nibh ornare, ut eleifend justo mollis. Vivamus pretium nunc non ante commodo, nec varius ligula sollicitudin. Nam id pulvinar sem. Suspendisse.</p></div><div class=privacy-section><h2>Section Title</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique facilisis bibendum. Duis dictum, justo ac egestas accumsan, est magna porta nunc, at ultricies elit urna nec eros. Etiam arcu velit, posuere sed ante quis, placerat mattis ipsum. Vestibulum rhoncus ex quis nibh ornare, ut eleifend justo mollis. Vivamus pretium nunc non ante commodo, nec varius ligula sollicitudin. Nam id pulvinar sem. Suspendisse.</p></div><div class=privacy-section><h2>Section Title</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique facilisis bibendum. Duis dictum, justo ac egestas accumsan, est magna porta nunc, at ultricies elit urna nec eros. Etiam arcu velit, posuere sed ante quis, placerat mattis ipsum. Vestibulum rhoncus ex quis nibh ornare, ut eleifend justo mollis. Vivamus pretium nunc non ante commodo, nec varius ligula sollicitudin. Nam id pulvinar sem. Suspendisse.</p></div></div></div></div>')
ContentManagementPage.create(page: "how-to-appeal-facebook" , content: '<h2> Facebook </h2><div class="appeal-question"><h2><span> 1 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 2 </span> How can users appeal? </h2><p> <span> A </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p><p> <span> B </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 3 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div>')
ContentManagementPage.create(page: "how-to-appeal-twitter" , content: '<h2> Twitter </h2><div class="appeal-question"><h2><span> 1 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 2 </span> How can users appeal? </h2><p> <span> A </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p><p> <span> B </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 3 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div>')
ContentManagementPage.create(page: "how-to-appeal-youtube" , content: '<h2> Youtube </h2><div class="appeal-question"><h2><span> 1 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 2 </span> How can users appeal? </h2><p> <span> A </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p><p> <span> B </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 3 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div>')
ContentManagementPage.create(page: "how-to-appeal-google" , content: '<h2> Google </h2><div class="appeal-question"><h2><span> 1 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 2 </span> How can users appeal? </h2><p> <span> A </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p><p> <span> B </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 3 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div>')
ContentManagementPage.create(page: "how-to-appeal-instagram" , content: '<h2> Instagram </h2><div class="appeal-question"><h2><span> 1 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 2 </span> How can users appeal? </h2><p> <span> A </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p><p> <span> B </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 3 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div>')
ContentManagementPage.create(page: "how-to-appeal-flickr" , content: '<h2> Flickr </h2><div class="appeal-question"><h2><span> 1 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 2 </span> How can users appeal? </h2><p> <span> A </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p><p> <span> B </span> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div><div class="appeal-question"><h2><span> 3 </span> What can users appeal? </h2><p> Facebook allows users to appeal the removal of a profile or page, but not the removal of individual posts, photos or videos. </p></div>')
ContentManagementPage.create(page: "submit-report" , content: '<div class="white-box"><div class="row"><div class="col-md-6"><h2> Why Submit? </h2><p> OnlineCensorship.org exists in order to provide an independent source ofinformation on how social media platforms are governing spaces for discourseonline. By crowdsourcing user-generated data on content removals, accountsuspensions and appeals, we hope to provide actionable information that canhelp companies become more accountable to their users, and to ensure thatcontent moderation is conducted both transparently and in the user’s bestinterest. </p></div><div class="col-md-6"><h2> What Should I Submit? </h2><p> Our reporting tool will direct you through a series of questions on the contentand process through which you were notified by the company. If you havescreenshots or copies of any messages sent to you by the company, pleasesubmit that to us, too - as much detail as you’re able to provide will help us toget a fuller picture of the way the content was moderated. If you’re willing,you’ll also have the opportunity to tell us a more detailed story about whathappened or provide us contact details so that we can follow up with you. </p></div></div></div><div class="white-box"><h2> What Will Happen Next? </h2><div class="columns"><p> The data you submit will be used in several ways: </p><p> - To learn more about how social media companies enforce their terms of service </p><p> - To understand how content takedown and account deactivation practices affect the lives and work of individuals in different parts of the world. </p><p> - To understand how content takedown and account deactivation is affecting political movements, activists, and journalists in different parts of the world. </p><p> - To engage with companies on how they can improve their regulations and reporting mechanisms and processes. </p><p> - To raise public awareness about the ways that social media companies regulate speech and how users are affected. </p><p>Even if you choose to remain anonymous, the data you provide will help us to gain a fuller picture of how companies are enforcing their terms of service to regulate content online. We plan to provide reports and visualizations once we have a sufficient pool of data. Some submissions may be integrated into case studies or analyses when we notice particular trends (but any identifiable data will only be used with your permission, of course). </p><p> If you haven’t already, you may be able to appeal the removal of your account orcontent. We’ve put together a handy resource guide on the appeals processesof several companies, available <a href="/resources/how-to-appeal">here</a>. </p><p> We have a strong commitment to privacy. Information that you submit to uswill not be shared with third parties without your express permission. See our <a href="/privacy-policy">Privacy policy</a>. </p></div></div>')

# home page fields
HomeField.create(slogan: 'If you feel that your content or account has been erroneously or unjustly removed from a social media platform, submit a report and let us know.',
	what_oc_title: 'WHAT IS ONLINE CENSORSHIP?',
	what_oc_text: 'Fixie tote bag ethnic keytar. Neutra vinyl American Apparel kale chips tofu art party, cardigan raw denim quinoa. Cray paleo tattooed, Truffaut skateboard street art PBR jean shorts Shoreditch farm-to-table Austin lo-fi Odd Future occupy. Chia semiotics skateboard, Schlitz messenger bag master cleanse High Life occupy vegan polaroid tote bag leggings.',
	appeal_text: 'WHAT TO KNOW HOW TO APPEAL ON SOCIAL MEDIA?',
	appeal_btn_text: 'READ MORE ABOUT APPEAL PROCESSES',
	submit_btn_text: 'Submit')


# Create Faq questions and answers
Faq.create(question: "Is onlinecensorship.org in any way affiliated with Facebook, Instagram, Flickr, Twitter, Google, or YouTube?" ,answer: "No.",theorder: 1)
Faq.create(question: "Why are you doing this?" ,answer: "While “censorship” is often used to refer to the suppression of public speech by government, the Internet as we know it is no longer a truly public space. Most online platforms through which we choose to express ourselves—and upon which many of us increasingly depend—are privately owned and operated. With these social media platforms replacing a truly open ‘public sphere,’ we need to be asking some serious questions about the role of companies in defining what is or is not ‘acceptable’ public speech. <p>We believe that OnlineCensorship.org can play an important role in holding Internet companies publicly accountable for the way in which they exercise power over people’s digital lives.</p>",theorder: 2)
Faq.create(question: "Who runs this website?" ,answer: "OnlineCensorship.org is a project of the Electronic Frontier Foundation and Visualizing Impact. Learn more about our team here.",theorder: 3)
Faq.create(question: "I am not very familiar with these issues. How can I learn more?" ,answer: "We have a collection of useful articles and books on our <a href='#''>resource</a> page, or check out our <a href='#''>blog</a>.",theorder: 4)
Faq.create(question: "How did you choose the platforms that are represented on this site?" ,answer: "When we first launched the site in 2012, we focused on the biggest platforms at that time: Facebook, Twitter, Flickr, Google+, and YouTube. We are currently researching other major social media platforms around the world and will add more soon. If you have a suggestion, please contact us.",theorder: 5)
Faq.create(question: "What are you doing with the data submitted by site users, and do you track submission sources in any way?" ,answer: "<p>We will use the information submitted in several ways:</p>
	        <ul>
	        	<li> To learn more about how social media companies enforce their terms of service. </li>
	        	<li> To understand how content takedown and account deactivation practices affect the lives and work of individuals in different parts of the world. </li>
	        	<li> To engage with companies on how they can improve their regulations and reporting mechanisms and processes. </li>
	        	<li> To raise public awareness about the ways that social media companies regulate speech and how users are affected. </li>
	        </ul><p>We have a strong commitment to privacy. Information that you submit to us will not be shared with third parties without your express permission. See our privacy policy.</p>",theorder: 7)
Faq.create(question: "What if I can’t access Facebook/Flickr/Twitter/Youtube/Google+ at all? All I get is an error message in my browser. Whose fault is that? What can I do about it?" ,answer: "If you can’t access the service at all, most likely that company is not trying to block you. Instead, the problem could be caused by one of any number of things.  Perhaps the site is experiencing technical problems.  Otherwise, it might be the result of filtering, which can come in many forms. Maybe it is being filtered by whoever controls Internet access at your office, school, cafe or wherever you are currently using the Internet because they don’t want you accessing certain sites or content. Or perhaps your Internet service provider (ISP) is blocking the service. In some countries, government authorities block certain social media services or instruct ISPs to do so.  All of these are forms of filtering.<p>If you would like to file a report about the fact that you cannot access a social media website from your location, please visit <a href='http://herdict.org/' target='_blank'>Herdict.org</a>, which specializes in tracking Internet filtering around the world.</p>",theorder: 8)
Faq.create(question: "What about smaller, start-up companies?" ,answer: "While we have focused on a limited number of popular platforms, this phenomenon is not limited to large companies. Similar issues are experienced by users of smaller, startup social media platforms as well. We hope that, by documenting censorship on major platforms, we will be able to inform the public as well as the entrepreneur community about the dangers of policing online speech.",theorder: 9)
Faq.create(question: "What if I have a suggestion?" ,answer: "Please email us: <a href='mailto:info@onlinecensorship.org'>info@onlinecensorship.org</a>",theorder: 10)
Faq.create(question: "How can I support your work?" ,answer: "Please make a donation via <a href='https://www.eff.org/' target='_blank'>EFF</a> with a note that your contribution is for OnlineCensorship.org. Your contribution will help make our project sustainable.",theorder: 11)

# Create default countries
Country.create(name: "Abkhazia")
Country.create(name: "Afghanistan")
Country.create(name: "Albania")
Country.create(name: "Algeria")
Country.create(name: "American Samoa")
Country.create(name: "Andorra")
Country.create(name: "Angola")
Country.create(name: "Anguilla")
Country.create(name: "Antarctica")
Country.create(name: "Antigua and Barbuda")
Country.create(name: "Argentina")
Country.create(name: "Armenia")
Country.create(name: "Aruba")
Country.create(name: "Australia")
Country.create(name: "Austria")
Country.create(name: "Azerbaijan")
Country.create(name: "Azores")
Country.create(name: "Bahamas")
Country.create(name: "Bahrain")
Country.create(name: "Bangladesh")
Country.create(name: "Barbados")
Country.create(name: "Belarus")
Country.create(name: "Belgium")
Country.create(name: "Belize")
Country.create(name: "Benin")
Country.create(name: "Bermuda")
Country.create(name: "Bhutan")
Country.create(name: "Bolivia")
Country.create(name: "Bosnia and Herzegovina")
Country.create(name: "Botswana")
Country.create(name: "Bouvet Island")
Country.create(name: "Brazil")
Country.create(name: "Brunei")
Country.create(name: "Bulgaria")
Country.create(name: "Burkina Faso")
Country.create(name: "Burma")
Country.create(name: "Burundi")
Country.create(name: "Cambodia")
Country.create(name: "Cameroon")
Country.create(name: "Canada")
Country.create(name: "Canary Islands")
Country.create(name: "Cape Verde")
Country.create(name: "Cayman Islands")
Country.create(name: "Central African Republic")
Country.create(name: "Chad")
Country.create(name: "Channel Islands")
Country.create(name: "Chile")
Country.create(name: "China")
Country.create(name: "Christmas IS")
Country.create(name: "Colombia")
Country.create(name: "Comoros")
Country.create(name: "Congo")
Country.create(name: "Cook Islands")
Country.create(name: "Costa Rica")
Country.create(name: "Cote d'Ivoire")
Country.create(name: "Croatia")
Country.create(name: "Cuba")
Country.create(name: "Cyprus")
Country.create(name: "Czech Republic")
Country.create(name: "Dem Rep of The Congo")
Country.create(name: "Denmark")
Country.create(name: "Djibouti")
Country.create(name: "Dominica")
Country.create(name: "Dominican Republic")
Country.create(name: "East Timor")
Country.create(name: "Ecuador")
Country.create(name: "Egypt")
Country.create(name: "El Salvador")
Country.create(name: "Equatorial Guinea")
Country.create(name: "Eritrea")
Country.create(name: "Estonia")
Country.create(name: "Ethiopia")
Country.create(name: "Falkland IS")
Country.create(name: "Faroe Islands")
Country.create(name: "Fiji")
Country.create(name: "Finland")
Country.create(name: "France")
Country.create(name: "French Guiana")
Country.create(name: "French Polynesia")
Country.create(name: "Gabon")
Country.create(name: "Gambia")
Country.create(name: "Georgia")
Country.create(name: "Germany")
Country.create(name: "Ghana")
Country.create(name: "Gibraltar")
Country.create(name: "Greece")
Country.create(name: "Greenland")
Country.create(name: "Grenada")
Country.create(name: "Guadeloupe")
Country.create(name: "Guam")
Country.create(name: "Guatemala")
Country.create(name: "Guernsey")
Country.create(name: "Guinea")
Country.create(name: "Guinea-Bissau")
Country.create(name: "Guyana")
Country.create(name: "Haiti")
Country.create(name: "Honduras")
Country.create(name: "Hong Kong")
Country.create(name: "Hungary")
Country.create(name: "India")
Country.create(name: "Indonesia")
Country.create(name: "Iran")
Country.create(name: "Iraq")
Country.create(name: "Ireland")
Country.create(name: "Isle of Man")
Country.create(name: "Italy")
Country.create(name: "Jamaica")
Country.create(name: "Japan")
Country.create(name: "Jersey")
Country.create(name: "Jordan")
Country.create(name: "Kazakhstan")
Country.create(name: "Kenya")
Country.create(name: "Kiribati")
Country.create(name: "Korea, North")
Country.create(name: "Korea, South")
Country.create(name: "Kosovo")
Country.create(name: "Kuwait")
Country.create(name: "Kyrgyzstan")
Country.create(name: "Laos")
Country.create(name: "Latvia")
Country.create(name: "Lebanon")
Country.create(name: "Lesotho")
Country.create(name: "Liberia")
Country.create(name: "Libya")
Country.create(name: "Liechtenstein")
Country.create(name: "Lithuania")
Country.create(name: "Luxembourg")
Country.create(name: "Macao")
Country.create(name: "Macedonia")
Country.create(name: "Madagascar")
Country.create(name: "Madeira IS")
Country.create(name: "Malawi")
Country.create(name: "Malaysia")
Country.create(name: "Maldives")
Country.create(name: "Mali")
Country.create(name: "Malta")
Country.create(name: "Marshall IS")
Country.create(name: "Martinique")
Country.create(name: "Mauritania")
Country.create(name: "Mauritius")
Country.create(name: "Mayotte")
Country.create(name: "Mexico")
Country.create(name: "Moldova")
Country.create(name: "Monaco")
Country.create(name: "Mongolia")
Country.create(name: "Montenegro")
Country.create(name: "Montserrat")
Country.create(name: "Morocco")
Country.create(name: "Mozambique")
Country.create(name: "Namibia")
Country.create(name: "Nauru")
Country.create(name: "Nepal")
Country.create(name: "Netherlands")
Country.create(name: "Netherlands Antilles")
Country.create(name: "New Caledonia")
Country.create(name: "New Zealand")
Country.create(name: "Nicaragua")
Country.create(name: "Niger")
Country.create(name: "Nigeria")
Country.create(name: "Norfolk IS")
Country.create(name: "Northern Ireland")
Country.create(name: "Norway")
Country.create(name: "Oman")
Country.create(name: "Pakistan")
Country.create(name: "Palau")
Country.create(name: "Palestine")
Country.create(name: "Panama")
Country.create(name: "Papua New Guinea")
Country.create(name: "Paraguay")
Country.create(name: "Peru")
Country.create(name: "Philippines")
Country.create(name: "Pitcairn IS")
Country.create(name: "Poland")
Country.create(name: "Portugal")
Country.create(name: "Puerto Rico")
Country.create(name: "Qatar")
Country.create(name: "Reunion IS")
Country.create(name: "Romania")
Country.create(name: "Russia")
Country.create(name: "Rwanda")
Country.create(name: "Samoa")
Country.create(name: "Saudi Arabia")
Country.create(name: "Senegal")
Country.create(name: "Serbia")
Country.create(name: "Seychelles")
Country.create(name: "Sierra Leone")
Country.create(name: "Singapore")
Country.create(name: "Slovakia")
Country.create(name: "Slovenia")
Country.create(name: "Somalia")
Country.create(name: "South Africa")
Country.create(name: "South Georgia")
Country.create(name: "Sri Lanka")
Country.create(name: "ST Kitts & Nevis")
Country.create(name: "Sudan")
Country.create(name: "Suriname")
Country.create(name: "Swaziland")
Country.create(name: "Sweden")
Country.create(name: "Switzerland")
Country.create(name: "Syria")
Country.create(name: "Taiwan")
Country.create(name: "Tajikistan")
Country.create(name: "Tanzania")
Country.create(name: "Thailand")
Country.create(name: "Togo")
Country.create(name: "Tonga")
Country.create(name: "Trinidad and Tobago")
Country.create(name: "Tunisia")
Country.create(name: "Turkey")
Country.create(name: "Turkmenistan")
Country.create(name: "Turks & Caicos IS")
Country.create(name: "Tuvalu")
Country.create(name: "Uganda")
Country.create(name: "Ukraine")
Country.create(name: "United Arab Emirates")
Country.create(name: "United Kingdom")
Country.create(name: "United States of America")
Country.create(name: "Uruguay")
Country.create(name: "US Minor Outlying IS")
Country.create(name: "Uzbekistan")
Country.create(name: "Vanuatu")
Country.create(name: "Vatican City")
Country.create(name: "Venezuela")
Country.create(name: "Vietnam")
Country.create(name: "Yemen")
Country.create(name: "Zimbabwe")


# Create default languages
Language.create(name: "English")
Language.create(name: "Abkhaz")
Language.create(name: "Adyghe")
Language.create(name: "Afrikaans")
Language.create(name: "Akan")
Language.create(name: "Albanian")
Language.create(name: "American Sign Language")
Language.create(name: "Amharic")
Language.create(name: "Arabic")
Language.create(name: "Aragonese")
Language.create(name: "Aramaic")
Language.create(name: "Armenian")
Language.create(name: "Aymara")
Language.create(name: "Balinese")
Language.create(name: "Basque")
Language.create(name: "Betawi")
Language.create(name: "Bosnian")
Language.create(name: "Breton")
Language.create(name: "Bulgarian")
Language.create(name: "Cantonese")
Language.create(name: "Catalan")
Language.create(name: "Cherokee")
Language.create(name: "Chickasaw")
Language.create(name: "Chinese")
Language.create(name: "Coptic")
Language.create(name: "Cornish")
Language.create(name: "Corsican")
Language.create(name: "Crimean Tatar")
Language.create(name: "Croatian")
Language.create(name: "Czech")
Language.create(name: "Danish")
Language.create(name: "Dutch")
Language.create(name: "Dawro")
Language.create(name: "Esperanto")
Language.create(name: "Estonian")
Language.create(name: "Ewe")
Language.create(name: "Hindi")
Language.create(name: "Filipino")
Language.create(name: "Finnish")
Language.create(name: "French")
Language.create(name: "Galician")
Language.create(name: "Georgian")
Language.create(name: "German")
Language.create(name: "Greek, Modern")
Language.create(name: "Ancient Greek")
Language.create(name: "Greenlandic")
Language.create(name: "Haitian Creole")
Language.create(name: "Hawaiian")
Language.create(name: "Hebrew")
Language.create(name: "Hindi")
Language.create(name: "Hungarian")
Language.create(name: "Icelandic")
Language.create(name: "Indonesian")
Language.create(name: "Inuktitut")
Language.create(name: "Interlingua")
Language.create(name: "Irish")
Language.create(name: "Italian")
Language.create(name: "Japanese")
Language.create(name: "Kabardian")
Language.create(name: "Kannada")
Language.create(name: "Kashubian")
Language.create(name: "Khmer")
Language.create(name: "Kinyarwanda")
Language.create(name: "Korean")
Language.create(name: "Kurdish/Kurdî")
Language.create(name: "Ladin")
Language.create(name: "Latgalian")
Language.create(name: "Latin")
Language.create(name: "Lingala")
Language.create(name: "Livonian")
Language.create(name: "Lojban")
Language.create(name: "Lower Sorbian")
Language.create(name: "Low German")
Language.create(name: "Macedonian")
Language.create(name: "Malay")
Language.create(name: "Malayalam")
Language.create(name: "Mandarin")
Language.create(name: "Manx")
Language.create(name: "Maori")
Language.create(name: "Mauritian Creole")
Language.create(name: "Min Nan")
Language.create(name: "Mongolian")
Language.create(name: "Norwegian")
Language.create(name: "Old Armenian")
Language.create(name: "Old English")
Language.create(name: "Old French")
Language.create(name: "Old Norse")
Language.create(name: "Old Prussian")
Language.create(name: "Oriya")
Language.create(name: "Pangasinan")
Language.create(name: "Papiamentu")
Language.create(name: "Pashto")
Language.create(name: "Persian")
Language.create(name: "Pitjantjatjara")
Language.create(name: "Polish")
Language.create(name: "Portuguese")
Language.create(name: "Proto-Slavic")
Language.create(name: "Quenya")
Language.create(name: "Rapa Nui")
Language.create(name: "Romanian")
Language.create(name: "Russian")
Language.create(name: "Sanskrit")
Language.create(name: "Scots")
Language.create(name: "Scottish Gaelic")
Language.create(name: "Serbian")
Language.create(name: "Serbo-Croatian")
Language.create(name: "Slovak")
Language.create(name: "Slovene")
Language.create(name: "Spanish")
Language.create(name: "Sinhalese")
Language.create(name: "Swahili")
Language.create(name: "Swedish")
Language.create(name: "Tagalog")
Language.create(name: "Tajik")
Language.create(name: "Tamil")
Language.create(name: "Tarantino")
Language.create(name: "Telugu")
Language.create(name: "Thai")
Language.create(name: "Tok Pisin")
Language.create(name: "Turkish")
Language.create(name: "Twi")
Language.create(name: "Ukrainian")
Language.create(name: "Upper Sorbian")
Language.create(name: "Urdu")
Language.create(name: "Uzbek")
Language.create(name: "Venetian")
Language.create(name: "Vietnamese")
Language.create(name: "Vilamovian")
Language.create(name: "Volapük")
Language.create(name: "Võro")
Language.create(name: "Welsh")
Language.create(name: "Xhosa")
Language.create(name: "Yiddish")
